checks:
  golint:
    filters:
    - value: should have comment or be unexported
    - value: or a comment on this block
    - value: vendor/github.com/golang/go/
  novendor:
    config:
      ignore-pkgs:
      - ./vendor/github.com/golang/go
