products:
  gofmt-1.10.0-asset:
    build:
      main-pkg: ./gofmt-1.10.0
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
group-id: com.palantir.godel
