plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: "com.palantir:amalgomate-plugin:1.3.0"
exclude:
  names:
    - "\\..+"
    - "vendor"
    - "generated_src"
  paths:
    - "godel"
