plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.41.0
        checksums:
          darwin-amd64: eb16881a03277eaeb5f978d67b274d54096bd8fa884d78b256e8bc58f342bae6
          linux-amd64: 7a7b81b485ed1a2458183eec19a048fd884de555af4bf3ed0940198f81ac676c
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.43.0
        checksums:
          darwin-amd64: 39765ffae9b437a09b98d6377bdd7af945a69a8dbb028c1f3659924bfade35cd
          linux-amd64: 4d0b71b29e946d37935664a4e53082f6af46a71a17fd35cbf934364f45507e76
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
  - \..+
  - vendor
  - generated_src
  paths:
  - godel
